# Generated by Django 4.2.3 on 2023-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('accounts', '0002_alter_user_courses_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='user', to='colleges.course'),
        ),
    ]
