# Generated by Django 4.2.3 on 2023-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
