# Generated by Django 4.2.3 on 2023-08-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_company_admin',
            new_name='is_college_admin',
        ),
    ]
