# Generated by Django 4.2.3 on 2023-08-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_is_company_admin_user_is_college_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_User', 'Can view User'), ('add_User', 'Can add User'), ('change_User', 'Can change User'), ('delete_User', 'Can delete User')]},
        ),
    ]
