# Generated by Django 4.2.3 on 2023-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_role_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
