# Generated by Django 4.2.3 on 2023-08-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colleges', '0004_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CollegeGroup',
        ),
        migrations.AlterModelOptions(
            name='collegegroup',
            options={},
        ),
        migrations.AlterModelTable(
            name='collegegroup',
            table='college_group',
        ),
    ]
