# Generated by Django 4.2.3 on 2023-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_rename_group_collegegroup_alter_collegegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegroup',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
