# Generated by Django 4.2.3 on 2023-08-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_alter_collegegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegroup',
            name='group_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegegroup',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterUniqueTogether(
            name='collegegroup',
            unique_together={('college', 'group_name')},
        ),
    ]
