# Generated by Django 4.2.3 on 2023-08-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_collegegroup_group_name_alter_collegegroup_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegroup',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
            preserve_default=False,
        ),
    ]
