# Generated by Django 4.2.3 on 2023-08-03 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_alter_collegegroup_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegroup',
            name='group_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
