# Generated by Django 4.2.3 on 2023-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_alter_collegegroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegroup',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
