# Generated by Django 4.2.3 on 2023-08-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_alter_collegegroup_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colleges.course')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colleges.college')),
            ],
        ),
    ]
