# Generated by Django 4.2.3 on 2023-08-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0012_rename_course_subject_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'college')},
        ),
    ]
