# Generated by Django 4.2.3 on 2023-08-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_alter_role_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='role',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course'),
        ),
    ]
